use_frameworks!

platform :ios, '9.0'

target 'ZBObjectiveCBeaver_Example' do
  pod 'ZBObjectiveCBeaver', :path => '../'

  target 'ZBObjectiveCBeaver_Tests' do
    inherit! :search_paths

    
  end
end
