use_frameworks!

platform :ios, '9.0'

#warn_for_unused_master_specs_repo => false

target 'ZBObjectiveCBeaver_Example' do
  pod 'ZBObjectiveCBeaver', :path => '../'

  target 'ZBObjectiveCBeaver_Tests' do
    inherit! :search_paths

    
  end
end
